# config/_default/hugo.yaml
cascade:
  # Posts - idioma por defecto en raíz (sin subcarpeta)
  - _target: { path: /post/**, kind: page }
    profile: true
    share: false

  # Blog - idioma por defecto en raíz
  - _target: { path: /blog/**, kind: page }
    profile: true
    share: false

  # Español
  - _target: { path: /es/post/**, kind: page }
    profile: true
    share: false
  - _target: { path: /es/blog/**, kind: page }
    profile: true
    share: false

  # Inglés (si usan subcarpeta /en/)
  - _target: { path: /en/post/**, kind: page }
    profile: true
    share: false
  - _target: { path: /en/blog/**, kind: page }
    profile: true
    share: false

# Páginas informativas (no posts)
cascade:
  - _target: { path: /page/**, kind: page }
    profile: false
    share: false
  - _target: { path: /es/page/**, kind: page }
    profile: false
    share: false
  - _target: { path: /en/page/**, kind: page }
    profile: false
    share: false
