# config/_default/hugo.yaml
cascade:
  # Posts - idioma por defecto en raíz (sin subcarpeta)
  - _target: { path: /post/**, kind: page }
    profile: true
    share: false

  # Blog - idioma por defecto en raíz
  - _target: { path: /blog/**, kind: page }
    profile: true
    share: false

  # Español
  - _target: { path: /es/post/**, kind: page }
    profile: true
    share: false
  - _target: { path: /es/blog/**, kind: page }
    profile: true
    share: false

  # Inglés (si usan subcarpeta /en/)
  - _target: { path: /en/post/**, kind: page }
    profile: true
    share: false
  - _target: { path: /en/blog/**, kind: page }
    profile: true
    share: false

cascade:
  # 0) DEFAULT GLOBAL: todas las páginas de content/**
  - target:
      kind: page
      path: "/**"
    profile: false
    share: false

  # 1) Excepciones: posts/blog (mantener tarjeta de autor), ES y EN
  - target: { kind: page, path: "/post/**" }
    profile: true
    share: false
  - target: { kind: page, path: "/blog/**" }
    profile: true
    share: false
  - target: { kind: page, path: "/es/post/**" }
    profile: true
    share: false
  - target: { kind: page, path: "/es/blog/**" }
    profile: true
    share: false
  - target: { kind: page, path: "/en/post/**" }
    profile: true
    share: false
  - target: { kind: page, path: "/en/blog/**" }
    profile: true
    share: false

