# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.
  

[[main]]
name = "About MD"
url = ""
weight = 10
#  [[main]]
#  name = "Origen"
#  url = ""
#  parent = "About MD"
#    weight = 10
  [[main]]
  name = "Mission y Vision"
  url = "authors/metadocencia/"
  parent = "About MD"
    weight = 20
#  [[main]]
#  name = "Values"
#  url = ""
#  parent = "About MD"
#    weight = 30
#  [[main]]
#  name = "Code of Conduct"
#  url = "authors/metadocencia/cdc/"
#  parent = "About MD"
#    weight = 40
[[main]]
  name = "Accesibility"
  url = "post/accessibility_profiles/"
  parent = "About MD"
    weight = 50
  [[main]]
  name = "Team"
  url = "equipo/"
  parent = "About MD"
    weight = 50
  [[main]]
  name = "Ex Members"
  url = "equipo/"
  parent = "About MD"
    weight = 50



[[main]]
name = "Curricula"
url = ""
weight = 20
  [[main]]
  name = "Courses"
  url = "cursos/"
  parent = "Curricula"
  weight = 10
 #[[main]]
 #  name = "Presentaciones"
 #  url = "#talks"
 #  parent = "Curricula"
 #  weight = 20
  # [[main]]
 # name = "Typologies"
 # url = ""
 # parent = "Curricula"
 #   weight = 30
 # [[main]]
 # name = "Agenda"
 # url = ""
 # parent = "Curricula"
 #   weight = 40
 # [[main]]
 # name = "Enrollment"
 # url = ""
 # parent = "Curricula"
 #   weight = 50


 [[main]]
  name = "Events"
  url = "events/"
  weight = 40


[[main]]
name = "Supporters"
url = ""
weight = 30
  [[main]]
  name = "Sponsors"
  url = "sponsors/"
  parent = "Supporters"
    weight = 10
  [[main]]
  name = "Donate"
  url = "donar/"
  parent = "Supporters"
    weight = 20
  [[main]]
  name = "Get involved"
  url = "#contact"
  parent = "Supporters"
    weight = 30


[[main]]
  name = "Publicaciones"
  url = ""
   weight = 40
  [[main]]
  name = "Blog"
  url = "#publicaciones"
  parent = "Publicaciones"
   weight = 10
  [[main]]
  name = "Press"
  url = "prensas"
  parent = "Publicaciones"
   weight = 20
 # [[main]]
 # name = "Boletines"
 # url = ""
 # parent = "Publicaciones"
 #  weight = 30



[[main]]
  name = "Contact"
  url = ""
  weight = 50
    [[main]]
    name = "Form"
    url = "#contact"
    parent = "Contact"
    weight = 10
#    [[main]]
#    name = "Social Media"
#    url = ""
#    parent = "Contact"
#    weight = 20    
    [[main]]
    name = "Newsletter"
    url = "https://netlify.us19.list-manage.com/subscribe/post?u=92fb89ce82f9689a3b083bb35&amp;id=d8187ceaf7"
    parent = "Contact"
    weight = 30
