# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.
  
[[main]]
name = "Sobre MD"
url = ""
weight = 10
#  [[main]]
#  name = "Origen"
#  url = ""
#  parent = "Sobre MD"
#    weight = 10
  [[main]]
  name = "Propuesta"
  url = "/propuesta"
  parent = "Sobre MD"
    weight = 20
#  [[main]]
#  name = "Manifiesto"
#  url = ""
#  parent = "Sobre MD"
#    weight = 30
  [[main]]
  name = "Código de conducta"
  url = ""
  parent = "Sobre MD"
    weight = 40
  [[main]]
  name = "Equipo"
  url = ""
  parent = "Sobre MD"
    weight = 50
  
[[main]]
name = "Cursos"
url = ""
weight = 20
  [[main]]
  name = "Propuestas"
  url = "cursos/"
  parent = "Cursos"
    weight = 10
  [[main]]
  name = "Tipologías"
  url = ""
  parent = "Cursos"
    weight = 20
  [[main]]
  name = "Agenda"
  url = ""
  parent = "Cursos"
    weight = 30
  [[main]]
  name = "Inscripciones"
  url = ""
  parent = "Cursos"
    weight = 40
  
[[main]]
name = "Apoyos"
url = ""
weight = 30
  [[main]]
  name = "Auspiciantes"
  url = "#sponsors"
  parent = "Apoyos"
    weight = 10
  [[main]]
  name = "Donar"
  url = "#donar"
  parent = "Apoyos"
    weight = 20
  [[main]]
  name = "Consultas"
  url = ""
  parent = "Apoyos"
    weight = 30

[[main]]
  name = "Publicaciones"
  url = ""
  weight = 40
  [[main]]
  name = "BLOG"
  url = "post/"
  parent = "Publicaciones"
    weight = 10
  [[main]]
    name = "Prensa"
    url = "#prensa"
    parent = "Publicaciones"
    weight = 20

[[main]]
  name = "Contacto"
  url = ""
  weight = 50
    [[main]]
    name = "Prensa"
    url = "./layouts/shortcodes/newsletter-mailchimp.html"
    parent = "Publicaciones"



# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
