# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.
  
[[main]]
  name = "Equipo"
  url = "#equipo"
  weight = 10
  
# [[main]]
#   name = "Presentaciones"
#   url = "#talks"
#   weight = 20

[[main]]
  name = "Materiales"
  url = "#materiales"
  weight = 50

[[main]]
  name = "Agradecimientos"
  url = "#agradecimientos"
  weight = 55

[[main]]
  name = "Auspiciantes"
  url = "#sponsors"
  weight = 57

[[main]]
  name = "Cursos"
  url = "cursos/"
  weight = 30

[[main]]
  name = "Contacto"
  url = "#contact"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
