# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
name = "Sobre MetaDocencia"
url = ""
weight = 10
#  [[main]]
#  name = "Origen"
#  url = ""
#  parent = "Sobre MetaDocencia"
#    weight = 10
  [[main]]
  name = "Misión y Visión"
  url = "authors/metadocencia/"
  parent = "Sobre MetaDocencia"
    weight = 20
  [[main]]
  name = "Valores"
  url = "authors/metadocencia/"
  parent = "Sobre MetaDocencia"
    weight = 30
  [[main]]
  name = "Pautas de convivencia"
  url = "cdc/"
  parent = "Sobre MetaDocencia"
    weight = 40
  [[main]]
  name = "Accesibilidad"
  url = "post/perfiles_accesibilidad/"
  parent = "Sobre MetaDocencia"
    weight = 50
  [[main]]
  name = "Equipo"
  url = "equipo/"
  parent = "Sobre MetaDocencia"
    weight = 60
#  [[main]]
#  name = "Ex Miembros"
#  url = "equipo/"
#  parent = "Sobre MetaDocencia"
#    weight = 70



[[main]]
name = "Qué hacemos"
url = ""
weight = 20
  [[main]]
  name = "Cursos"
  url = "cursos/"
  parent = "Qué hacemos"
  weight = 10
  [[main]]
  name = "Cursos"
  url = "cursos/"
  parent = "Qué hacemos"
  weight = 20
  [[main]]
  name = "Eventos"
  url = "eventos/"
  parent = "Qué hacemos"
    weight = 30
  [[main]]
  name = "Consultoría"
  url = "consultoria/"
  parent = "Qué hacemos"
    weight = 40
 # [[main]]
 # name = "Inscripciones"
 # url = ""
 # parent = "Qué hacemos"
 #   weight = 50


 [[main]]
  name = "Publicaciones"
  url = ""
   weight = 40
  [[main]]
  name = "Blog"
  url = "#publicaciones"
  parent = "Publicaciones"
   weight = 10
  [[main]]
  name = "Prensa"
  url = "prensas"
  parent = "Publicaciones"
   weight = 20
 # [[main]]
 # name = "Boletines"
 # url = ""
 # parent = "Publicaciones"
 #  weight = 30


[[main]]
name = "Apoyos"
url = ""
weight = 30
  [[main]]
  name = "Auspiciantes"
  url = "sponsors/"
  parent = "Apoyos"
    weight = 10
  [[main]]
  name = "Donar"
  url = "donar/"
  parent = "Apoyos"
    weight = 20
  [[main]]
  name = "Consultas"
  url = "#contact"
  parent = "Apoyos"
    weight = 30



[[main]]
  name = "Contacto"
  url = ""
  weight = 50
 [[main]]
   name = "Formulario"
   url = "#contact"
   parent = "Contacto"
   weight = 10
#    [[main]]
#    name = "Redes"
#    url = ""
#    parent = "Contacto"
#    weight = 20    
    [[main]]
    name = "Newsletter"
    url = "https://netlify.us19.list-manage.com/subscribe/post?u=92fb89ce82f9689a3b083bb35&amp;id=d8187ceaf7"
    parent = "Contacto"
    weight = 30



# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
