# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.
  

[[main]]
name = "About Us"
url = ""
weight = 10
#  [[main]]
#  name = "Origin"
#  url = ""
#  parent = "About Us"
#    weight = 10
  [[main]]
  name = "Mission and Vision"
  url = "authors/metadocencia/"
  parent = "About Us"
    weight = 20
#  [[main]]
#  name = "Values"
#  url = "en/values/"
#  parent = "About Us"
#    weight = 30
  [[main]]
  name = "Code of Conduct"
  url = "en/pdc/"
  parent = "About Us"
    weight = 40
  [[main]]
  name = "Accessibility"
  url = "/post/perfiles_accesibilidad/"
  parent = "About Us"
    weight = 50
  [[main]]
  name = "Team"
  url = "equipo/"
  parent = "About Us"
    weight = 60
      [[main]]
  name = "Fellow Communities"
  url = "hive/"
  parent = "About Us"
    weight = 70
#  [[main]]
#  name = "Former Contributors"
#  url = "equipo/"
#  parent = "About Us"
#    weight = 50



[[main]]
name = "What We Do"
url = ""
weight = 20
  [[main]]
  name = "Training"
  url = "cursos/"
  parent = "What We Do"
  weight = 10
  [[main]]
  name = "Events"
  url = "events/"
  parent = "What We Do"
  weight = 20
  [[main]]
  name = "Consulting"
  url = "consultoria/"
  parent = "What We Do"
  weight = 30
 #[[main]]
 # name = "Agenda"
 # url = ""
 # parent = "What We Do"
 #   weight = 40
 # [[main]]
 # name = "Enrollment"
 # url = ""
 # parent = "What We Do"
 #   weight = 50


[[main]]
  name = "News"
  url = ""
  weight = 30
  [[main]]
  name = "Blog"
  url = "post/"
  parent = "News"
  weight = 10
  [[main]]
  name = "Press"
  url = "prensa2"
  parent = "News"
  weight = 20
  [[main]]
  name = "Newsletters"
  url = "newsletter"
  parent = "News"
  weight = 30


[[main]]
name = "Supporters"
url = ""
weight = 40
  [[main]]
  name = "Sponsors"
  url = "sponsors/"
  parent = "Supporters"
    weight = 10
  [[main]]
  name = "Donate"
  url = "donar/"
  parent = "Supporters"
    weight = 20
  [[main]]
  name = "Get Involved"
  url = "contact/"
  parent = "Supporters"
    weight = 30


[[main]]
name = "Contact Us"
url = ""
weight = 50
  [[main]]
  name = "Form"
  url = "contact"
  parent = "Contact Us"
  weight = 10
#  [[main]]
#  name = "Social Media"
#  url = ""
#  parent = "Contact"
#  weight = 20    
  [[main]]
  name = "Newsletter"
  url = "https://netlify.us19.list-manage.com/subscribe/post?u=92fb89ce82f9689a3b083bb35&amp;id=d8187ceaf7"
  parent = "Contact Us"
  weight = 30
