imports:
  - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-core
  - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-bootstrap/v5
  - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-reveal

