# Deprecated: este archivo queda deshabilitado. Usamos config/_default/params.yaml.
# SITE SETUP
# Documentation: https://sourcethemes.com/academic/
#
############################
## Theme
############################
#
# [appearance]
# mode        = "auto"                      # "light" | "dark" | "auto"
# theme_day   = "metadocencia_theme"        # tu tema claro actual (archivo existente)
# theme_night = "metadocencia_theme"        # el archivo que creaste recién
#
#
# # Override the theme's font set (optional).
# #   Latest font sets (may require updating): https://sourcethemes.com/academic/themes/
# #   Browse built-in font sets in `themes/academic/data/fonts/`
# #   Browse user installed fonts in `data/fonts/`
# font = ""
#
# # Choose a font size.
# # Sizes: XS (extra small), S (small), M (medium), L (large - DEFAULT), XL (extra large)
# font_size = "M"
#
############################
## Basic Info
############################
#
# # Website type
# #   Improve how search engines understand your site.
# #   For personal sites, choose "Person".
# #   For organizations and projects, choose from https://schema.org/Organization#subtypes
# #   E.g. Person, Organization, LocalBusiness, Project, EducationalOrganization
# site_type = "EducationalOrganization"
#
# # Local business type (optional)
# # If you entered "LocalBusiness" above, choose the type of business from https://schema.org/LocalBusiness#subtypes
# local_business_type = ""
#
# # Organization name (optional)
# # Enter an organization or project name. Defaults to the site title from `config.toml`.
# org_name = ""
#
# # Description for social sharing and search engines. If undefined, superuser role is used in place.
# description = "Ciencia abierta para comunidades hispanohablantes"
#
############################
## Site Features
############################
#
# # Enable source code highlighting? true/false
# # Documentation: https://sourcethemes.com/academic/docs/writing-markdown-latex/#highlighting-options
# highlight = true
# highlight_languages = ["r"]  # Add support for highlighting additional languages
# # highlight_style = "github"  # For supported styles, see https://cdnjs.com/libraries/highlight.js/
#
# # Enable LaTeX math rendering? true/false
# #   If false, you can enable math on a per page basis as needed.
# math = false
#
# # Enable diagram rendering? true/false
# #   If false, you can enable diagrams on a per page basis as needed.
# diagram = false
#
# # Privacy pack
# #   Show a cookie consent message to visitors
# #   Anonymize IP in Google Analytics (if enabled)
# privacy_pack = false
# anonymize_ip = true
#
# # Enable visitors to edit pages?
# #   `repo` defines the repository URL. `editable` defines which page types can be edited.
# edit_page = {repo_url = "https://github.com/MetaDocencia/SitioWeb", content_dir = "", repo_branch = "master", editable = {docs = true, page = false, post = false}}
#
############################
## Contact details
## (se mueve a params.yaml)
############################
#
# email = "xeqzpkjn" # No borrar o cambiar
# # phone = "888 888 88 88"
#
# # address = {street = "450 Serra Mall", city = "Stanford", region = "CA", postcode = "94305", country = "United States", country_code = "US"}
# # coordinates = {latitude = "37.4275", longitude = "-122.1697"}
# # directions = "..."
# # office_hours = []
# # appointment_url = "https://calendly.com"
#
# # contact_links:
# #   - icon: envelope
# #     icon_pack: fas
# #     link: "mailto:hola@metadocencia.org"
# #     name: Email
# #   - icon: mastodon
# #     icon_pack: fab
# #     link: "https://floss.social/@MetaDocencia"
# #     name: Mastodon
# #   - icon: twitter
# #     icon_pack: fab
# #     link: "https://twitter.com/MetaDocencia"
# #     name: "Twitter/X"
# #   - icon: github
# #     icon_pack: fab
# #     link: "https://github.com/MetaDocencia"
# #     name: GitHub
# #   - icon: youtube
# #     icon_pack: fab
# #     link: "https://www.youtube.com/metadocencia"
# #     name: YouTube
# #   - icon: instagram
# #     icon_pack: fab
# #     link: "https://www.instagram.com/metadocencia/"
# #     name: Instagram
# #   - icon: linkedin
# #     icon_pack: fab
# #     link: "https://www.linkedin.com/company/metadocencia/"
# #     name: LinkedIn
# #   - icon: bluesky
# #     icon_pack: fab
# #     link: "https://bsky.app/profile/metadocencia.org"
# #     name: Bluesky
# #   - icon: slack
# #     icon_pack: fab
# #     link: "https://w3id.org/metadocencia/slack"
# #     name: Slack
# #   - icon: facebook
# #     icon_pack: fab
# #     link: "https://www.facebook.com/metadocencia"
# #     name: Facebook
#
############################
## Social
############################
#
# sharing_image = "logo-metadocencia.png"
# twitter = "metadocencia"
#
############################
## Regional Settings
############################
#
# date_format = "02/01/2006"
# time_format = "3:04 PM"
# address_format = "en-us"
#
############################
## Advanced
############################
#
# main_menu = {align = "l", show_logo = true}
# reading_time = true
# section_pager = true
# docs_section_pager = true
# sharing = false
# link_authors = true
# abstract_length = 135
# plugins_js  = []
#
# [avatar]
#   gravatar = false
#   shape = "circle"
#
# [address_formats]
#   en-us = {order = ['street', 'city', 'region', 'postcode'], delimiters = [', ', ', ', ' ', '']}
#   en-gb = {order = ['street', 'city', 'region', 'postcode'], delimiters = [', ', ', ', ', ', '']}
#   de = {order = ['street', 'postcode', 'city'], delimiters = ['<br>', ' ', '']}
#   fr-fr = {order = ['street', 'postcode', 'city'], delimiters = ['<br>', ' ', '']}
#   zh = {order = ['postcode', 'region', 'city', 'street'], delimiters = [' ', ' ', ' ', '']}
#
# [publications]
#   date_format = "January 2006"
#   citation_style = "apa"
#
# [projects]
#   post_view = 2
#   publication_view = 2
#   talk_view = 2
#
############################
## Comments
############################
#
# [comments]
#   engine = 0
#   commentable = {page = true, post = true, docs = true, project = true, publication = true, talk = true}
#   [comments.disqus]
#     shortname = ""
#     show_count = true
#   [comments.commento]
#     url = ""
#
############################
## Search
############################
#
# [search]
#   engine = 1
#   [search.algolia]
#     app_id = ""
#     api_key = ""
#     index_name = ""
#     show_logo = false
#
############################
## Maps
############################
#
# [map]
#   engine = 2
#   api_key = ""
#   zoom = 15
#
############################
## Marketing
############################
#
# [marketing]
#   google_analytics = "UA-161659380-1"
#   google_tag_manager = ""
