[build]
  command = "hugo --gc --minify"
  publish = "public"

# Producción (sin tocar, usa el baseURL que tienes en config.toml)
[context.production.environment]
  HUGO_ENV     = "production"
  HUGO_VERSION = "0.57.2"

# Deploy Previews: sobre-escribo el comando para inyectar su propia URL
[context.deploy-preview]
  command = "hugo --gc --minify --baseURL=${DEPLOY_PRIME_URL}/"

[context.deploy-preview.environment]
  HUGO_ENV     = "production"
  HUGO_VERSION = "0.125.0"
