# netlify.toml

[build]
  command   = "hugo --gc --minify"
  publish   = "public"

# Producción sigue con tu versión estable actual
[context.production.environment]
  HUGO_VERSION = "0.57.2"

# Para previews (PRs) uso Hugo 0.125.0 + activo el entorno production
[context.deploy-preview.environment]
  HUGO_VERSION = "0.125.0"
  HUGO_ENV     = "production"

# Para branch-deploys (si tienes configurado)
[context.branch-deploy.environment]
  HUGO_VERSION = "0.125.0"
  HUGO_ENV     = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --baseURL https://deploy-preview-274--metadocencia.netlify.app/"
