# ==============================
# Netlify build config (MD)
# ==============================

[build]
  # Prod por defecto (usa ${URL}/):
  command = "hugo mod vendor && hugo --gc --minify --baseURL ${URL}/ && npx -y pagefind --site 'public'"
  publish = "public"

[build.environment]
  HUGO_ENV           = "production"
  HUGO_VERSION       = "0.125.0"   # ← Prod sigue con la versión actual
  HUGO_ENABLEGITINFO = "true"
  NODE_VERSION       = "20"

# ---------- Producción ----------
[context.production]
  command = "hugo mod vendor && hugo --gc --minify --baseURL ${URL}/ && npx -y pagefind --site 'public'"

# ---------- Deploy Preview (PRs) ----------
[context.deploy-preview]
  command = "npm ci && npx update-browserslist-db@latest --update-db && hugo mod clean && hugo mod vendor && hugo --gc --minify --baseURL ${DEPLOY_PRIME_URL}/ && npx -y pagefind --site 'public'"
  [context.deploy-preview.environment]
    HUGO_ENV     = "production"
    HUGO_VERSION = "0.148.2"
    NODE_VERSION = "20"
    BROWSERSLIST_IGNORE_OLD_DATA = "1"

[context.branch-deploy]
  command = "npm ci && npx update-browserslist-db@latest --update-db && hugo mod clean && hugo mod vendor && hugo --gc --minify --baseURL ${DEPLOY_PRIME_URL}/ && npx -y pagefind --site 'public'"
  [context.branch-deploy.environment]
    HUGO_ENV     = "production"
    HUGO_VERSION = "0.148.2"
    NODE_VERSION = "20"
    BROWSERSLIST_IGNORE_OLD_DATA = "1"

