# ==============================
# Netlify build config (MD)
# ==============================

[build]
  command = "hugo mod vendor && hugo --gc --minify -b $URL && npx -y pagefind --site 'public'"
  publish = "public"


[build.environment]
  HUGO_ENV     = "production"
  HUGO_VERSION = "0.125.0"
  NODE_VERSION = "20"

# ---------- Producción ----------
[context.production]
  command = "hugo mod vendor && hugo --gc --minify -b $URL && npx -y pagefind --site 'public'"

[context.production.environment]
  HUGO_ENV     = "production"
  HUGO_VERSION = "0.125.0"
  NODE_VERSION = "20"

# ---------- Deploy Preview (PRs) ----------
[context.deploy-preview]
  command = "hugo mod vendor && hugo --gc --minify --baseURL ${DEPLOY_PRIME_URL}/ && npx -y pagefind --site 'public'"

[context.deploy-preview.environment]
  HUGO_ENV     = "production"
  HUGO_VERSION = "0.125.0"
  NODE_VERSION = "20"

# ---------- Branch Deploys ----------
[context.branch-deploy]
  command = "hugo mod vendor && hugo --gc --minify --baseURL ${DEPLOY_PRIME_URL}/ && npx -y pagefind --site 'public'"

[context.branch-deploy.environment]
  HUGO_ENV     = "production"
  HUGO_VERSION = "0.125.0"
  NODE_VERSION = "20"
