[build]
  command = "pnpm install && hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.148.2"
  NODE_VERSION = "20.0.0"
  HUGO_ENABLEGITINFO = "true"
  HUGO_SECURITY_FUNCS_GETENV = "^HUGO_|^CI$|^WC_POST_CSS$"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "pnpm install && hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "pnpm install && hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true

[[redirects]]
  from = "/en/*"
  to   = "/:splat"
  status = 301

[[redirects]]
  from = "/es/home/*"
  to   = "/:splat"
  status = 301

