# ==============================
# Netlify build config (MD)
# ==============================

[build]
  command = "hugo mod clean && hugo mod vendor && hugo --gc --minify --baseURL ${URL}/ && npx -y pagefind --site 'public'"
  publish = "public"

[build.environment]
  HUGO_ENV           = "production"
  HUGO_VERSION       = "0.150.0"   # >= 0.148.2 extended
  HUGO_ENABLEGITINFO = "true"
  NODE_VERSION       = "20"

# ---------- Producción ----------
[context.production]
  command = "hugo mod clean && hugo mod vendor && hugo --gc --minify --baseURL ${URL}/ && npx -y pagefind --site 'public'"

# ---------- Deploy Preview (PRs) ----------
[context.deploy-preview]
  command = "hugo mod clean && hugo mod vendor && hugo --gc --minify --baseURL ${DEPLOY_PRIME_URL}/ && npx -y pagefind --site 'public'"

# ---------- Branch Deploys (ramas sin PR) ----------
[context.branch-deploy]
  command = "hugo mod clean && hugo mod vendor && hugo --gc --minify --baseURL ${DEPLOY_PRIME_URL}/ && npx -y pagefind --site 'public'"
