# netlify.toml — limpio, sin tablas duplicadas

# Mapeo del Edge Function (usa el directorio por defecto: netlify/edge-functions)
[[edge_functions]]
  function = "maintenance"
  path = "/*"

# ===== Producción =====
[context.production.environment]
  HUGO_VERSION = "0.64.0"
  MAINT_ALLOWED_HOSTS = "metadocencia.org,www.metadocencia.org"
  # Ventana real: Jue 21/08/2025 19:00–22:00 ART = 22:00–01:00 UTC
  MAINT_START_UTC = "2025-08-21T22:00:00Z"
  MAINT_END_UTC   = "2025-08-22T01:00:00Z"
  MAINT_MESSAGE_ES = "Estamos trabajando en la renovación de nuestro sitio web. Este jueves 21 de agosto realizaremos tareas de mantenimiento, por lo que la página podría no estar disponible durante algunas horas."
  MAINT_MESSAGE_EN = "We are currently working on updating our website. Maintenance work will be carried out on Thursday 21 August, so the site may be unavailable for a few hours."
  MAINT_TEST_MODE  = "0"

# ===== Deploy Previews (PRs) =====
[context.deploy-preview.environment]
  HUGO_VERSION = "0.64.0"
  # Forzar banner en pruebas (o usar ?maint_test=1)
  MAINT_TEST_MODE = "1"
# Poné una ventana amplia para hoy (UTC) para descartar tema horario:
  MAINT_START_UTC = "2025-08-19T00:00:00Z"
  MAINT_END_UTC   = "2025-08-20T00:00:00Z"
  MAINT_MESSAGE_ES = "Estamos trabajando en la renovación de nuestro sitio web. (PRUEBA)"
  MAINT_MESSAGE_EN = "We are currently working on updating our website. (TEST)"
