---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/es
  label: Es
  create: all
  match: "**/*"
- type: directory
  path: content/en
  label: En
  create: all
  match: "**/*"
- type: directory
  path: config/_default/
  label: Config-default
  create: all
  match: "**/*"
- type: directory
  path: themes/hugo-academic/
  label: Themes-Hugo
  create: all
  match: "**/*"
- type: directory
  path: assets/images/
  label: Assets-images
  create: all
  match: "*"
- type: directory
  path: data/themes/
  label: Data-themes
  create: all
  match: "*"
- type: directory
  path: layouts/shortcodes/
  label: Layouts-shortcodes
  create: all
  match: "*"
- type: directory
  path: layouts/shortcodes/
  label: Layouts-shortcodes
  create: all
  match: "*"
- type: directory
  path: static/
  label: Static
  create: all
  match: "*"
- type: document
  path: config.toml
  label: archivo-config-toml
  create: all
  match: "*"
- type: document
  path: .Rprofile
  label: archivo-rprofile
  create: all
  match: "*"
- type: document
  path: .gitignore
  label: archivo-gitignore
  create: all
  match: "*"
- type: document
  path: README.md
  label: archivo-readme
  create: all
  match: "*"
- type: document
  path: SitioWeb.Rproj
  label: archivo-sitioweb-rproj
  create: all
  match: "*"
- type: document
  path: index.Rmd
  label: archivo-index-rmd
  create: all
  match: "*"
- type: document
  path: netlify.toml
  label: archivo-netlify-toml
  create: all
  match: "*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
