name: Build & Upload Preview Site

on:
  push:
    branches:
      - master
      - migracion-hugoblox

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.125.0'

      - name: Build site
        run: hugo --gc --minify

      - name: Upload public folder
        uses: actions/upload-artifact@v4   # ← actualizado a v4
        with:
          name: preview-site
          path: public/
